### PR TITLE
add datasets/UScrime.csv

### PR DESCRIPTION
**Pull request by kaunta**
tea_demo.ipynb doesn't work correctly if datasets/UScrime.csv doesn't exist.
Adding the dataset to the repo fixes that.

image

### CODE REVIEW

**Comment by MaLiN2223** [comment]
Is there a source/citation for this dataset?

**Comment by kaunta** [comment]
I grabbed it from [vincentarelbundock/Rdatasets](https://github.com/vincentarelbundock/Rdatasets/blob/master/csv/MASS/UScrime.csv).

**Comment by MaLiN2223** [comment]
I believe it would be good to add a license file to it. After that I think we should call @emjun for approval of this PR.

**Comment by emjun** [comment]
There's an original study that created the dataset. Let me dig it up!

**Comment by DustinAlandzes** [comment]
https://stat.ethz.ch/R-manual/R-devel/library/MASS/html/UScrime.html

>Ehrlich, I. (1973) Participation in illegitimate activities: a theoretical and empirical investigation. Journal of Political Economy, 81, 521–565.

>Venables, W. N. and Ripley, B. D. (1999) Modern Applied Statistics with S-PLUS. Third Edition. Springer. 

Looks like Rdatasets uses a GPL3 license and tea-lang uses Apache. Not sure if that's a problem
https://github.com/vincentarelbundock/Rdatasets/blob/master/license/GPL-3
https://github.com/emjun/tea-lang/blob/master/LICENSE.md

**Comment by MaLiN2223** [comment]
According to [Apache License manual](https://www.apache.org/licenses/GPL-compatibility.html): 

> GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

I am afraid we might need to abandon this PR :(

**Comment by emjun** [comment]
The R datasets come from published academic papers and can be found on CRAN and Rdatasets (comes from CRAN in the first place), so maybe we can at least point a) cite the academic papers and b) point to the Rdatasets repo and CRAN for users to find and download. 

What do you think @MaLiN2223 ?

**Comment by MaLiN2223** [comment]
@emjun I am not an expert in a copyright law but for me, pointing to the dataset (or even writing a script to download it for you) is the only good option here.

**Comment by kaunta** [comment]
@MaLiN2223 Ok. I added a few lines to the demo notebook to download the dataset using a provided URL.

image

**Review by MaLiN2223 — APPROVED** [review]
Looks good! :) 
@emjun, could we merge?

**Comment by emjun** [comment]
Awesome, @kaunta and @MaLiN2223 !!!

**Pull request merged**
