### PR TITLE
resolve csv with only header

### PR DESCRIPTION
**Pull request by rrrrrrockpang**

### CODE REVIEW

**Comment by emeryberger** [comment]
Hi @rrrrrrockpang - thanks for the PR! Can you explain and possibly provide an example to illustrate the problem that this PR addresses? Thanks!

**Comment by rrrrrrockpang** [comment]
Hi @emeryberger - thank you for following up. An error occurred when the input csv file is empty. For instance, I used the example [here](https://github.com/tea-lang-org/tea-lang/tree/master/examples/AR_TV) with an empty csv file (only has headers `,ID,Condition,Score`)

Error message:
```
Traceback (most recent call last):
  File "run.py", line 39, in <module>
    results = tea.hypothesize(['Score', 'Condition'], ['Condition:AR > TV'])
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/api.py", line 173, in hypothesize
    result = vardata_factory.create_vardata(dataset_obj, relationship, assumptions, study_design)
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/vardata_factory.py", line 56, in create_vardata
    return self.__create_relate_vardata(dataset, expr, assumptions, design)
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/vardata_factory.py", line 430, in __create_relate_vardata
    test_result = execute_test(dataset, design, expr.predictions, combined_data, test)
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/helpers/evaluateHelperMethods.py", line 1540, in execute_test
    stat_result = test_func(dataset, predictions, combined_data)
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/helpers/evaluateHelperMethods.py", line 595, in mannwhitney_u
    t_stat, p_val = mann_whitney_exact(data[0], data[1], alternative="greater")
  File "/Users/rockpang/PycharmProjects/tea/venv/lib/python3.8/site-packages/tea/helpers/evaluateHelperMethods.py", line 548, in mann_whitney_exact
    assert(cum_prob[len(cum_prob) - 1] <= 1.0 + epsilon)
AssertionError
```
This PR only returns the proper statistical tests by tea without executing it.

**Comment by rjust** [comment]
@emeryberger For context, the spec for this unexpected crash stems from the Tea paper:

> For pre-registration (further discussed in Section 9), the data set can be empty (with only column names).

In this case, Tea should only output the set of valid tests but not attempt to execute them.

@rrrrrrockpang Can you please add an example to your PR (e.g., under *examples/prereg*)? Feel free to copy the Tea script and (empty) data file from an existing example.  Additionally, adding a brief description about the issue and how to reproduce it (using the provided example) would be helpful.

Thanks,
René

**Comment by rrrrrrockpang** [comment]
Hi @rjust and @emeryberger, thanks for following up, and apologize for the lack of clarity.

Here is the code to reproduce the issue. Tea tries to execute valid tests when input dataset is empty. My PR only outputs the relevant test names in a list.

```
import tea  # Version: 0.3.1

# https://github.com/tea-lang-org/tea-lang/blob/master/examples/AR_TV/ar_tv_long.csv
# To reproduce the issue, remove the data and only keep the header `,ID,Condition,Score`
data_path = "./ar_tv_long.csv"
variables = [
    {
        'name': 'ID',
        'data type': 'ratio'
    },
    {
        'name': 'Condition',
        'data type': 'nominal',
        'categories': ['AR', 'TV']
    },
    {
        'name': 'Score',
        'data type': 'ordinal',
        'categories': [1,2,3,4,5]
    }
]
experimental_design = {
    'study type': 'experiment',
    'independent variables': 'Condition',
    'dependent variables': 'Score'
}
assumptions = {
    'Type I (False Positive) Error Rate': 0.01969
}
tea.data(data_path, key='ID')
tea.define_variables(variables)
tea.define_study_design(experimental_design)
tea.assume(assumptions)
results = tea.hypothesize(['Score', 'Condition'], ['Condition:AR > TV'])
```

**Comment by emeryberger** [comment]
Was able to reproduce (from repo version, not latest on pip - time for a new release, @emjun?). Thanks!

**Comment by emjun** [comment]
**Update:** 
Newest release fixes this bug: https://pypi.org/project/tealang/0.4.2/

@rrrrrrockpang @rjust 
Following up on this -- I had made a fix on my local branch and pushed to master after I told @rrrrrrockpang I'd fix the bug, but it seems that my changes never made it into the repo due to my remote origin url being the original Tea repo. (This worked fine for two years, but it looks like support for this is inconsistent.)

In any case, it looks like we got to a similar resolution/edit anyway. The current master repo has a combination of our changes. I am in the middle of adding a test for this fix. Once I do that, I will bump the version and reupload to Pypi. @emeryberger

**Pull request merged**
