### PR TITLE
Load from df

### PR DESCRIPTION
**Pull request by g-simmons2**
My attempt at allowing the user to load data from csv filepath or DataFrame object, see #19, and new demo notebook for an example.

Feedback welcome :)

### CODE REVIEW

**Comment by MaLiN2223** [comment]
I think you should rebase this PR, it seems like it contains a commit from #21 
Also, could you add some unit test presenting the functionality?

**Comment by emeryberger** [comment]
bump @g-simmons2 - this needs to be rebased to resolve conflicts.

**Comment by emeryberger** [comment]
Bump @g-simmons2

**Comment by emjun** [comment]
This PR might have duplicate functionality as https://github.com/emjun/tea-lang/pull/26#issue-361288714

**Comment by emjun** [comment]
Since this PR introduces functionality that has already been added and this thread has gone stale, I am going to close this PR. 

Nonetheless, thanks for the feature! Hope you'll contribute to other features, @g-simmons2 !

**Pull request closed without merging**
